#!/bin/bash -x
# open a shell in chroot and change to openturns user
#
# usage : ./chroot-enter [-32|-64|-c path_to_chroot] [root] command args...
#   if no command are given, bash is launched
#   "user" and "root" are verbotten command

CHROOTDIR64=/data/chroot/squeeze/x86_64
CHROOTDIR32=/data/chroot/squeeze/i386
CHROOTDIR=$CHROOTDIR64
if [ $# -gt 0 ]; then
  if [ "$1" == "-32" ]; then
    CHROOTDIR=$CHROOTDIR32
    shift
  elif [ "$1" == "-64" ]; then
    CHROOTDIR=$CHROOTDIR64
    shift
  elif [ "$1" == "-c" ]; then
    CHROOTDIR=$2
    shift 2
  fi
fi

STEP=chroot
USERNAME=openturns
if [ $# -gt 0 ]; then
  if [ "$1" == "root" ]; then
    USERNAME=root
    shift
  fi
  if [ "$1" == "user" ]; then
    STEP=user
    shift
  fi
fi

ARGS=bash
if [ $# -ne 0 ]; then
  ARGS="$@"
fi


# chroot to sys root dir
if [ "$STEP" == "chroot" ]; then

  # keep up to date script
  sudo cp $0 $CHROOTDIR/home/openturns

  # mount if not already mounted
  MOUNT=0
  if [ ! -e $CHROOTDIR/proc/cpuinfo ]; then
    #sudo mount -t proc proc $CHROOTDIR/proc
    sudo mount --bind /proc $CHROOTDIR/proc
    sudo mount --bind /dev $CHROOTDIR/dev
    sudo mount devpts -t devpts $CHROOTDIR/dev/pts
    #sudo mount -t sysfs sys $CHROOTDIR/sys
    sudo mount --bind /sys $CHROOTDIR/sys
    sudo mount -t binfmt_misc binfmt_misc $CHROOTDIR/proc/sys/fs/binfmt_misc
    MOUNT=1
  fi

  if [ "$USERNAME" == "openturns" ]; then
    CHROOT_ENTER_NAME=`basename $0`
    sudo chroot $CHROOTDIR /home/openturns/$CHROOT_ENTER_NAME user "$ARGS"
  else
    sudo chroot $CHROOTDIR "$ARGS"
  fi

  # the first chroot-enter umount !
  if [ "$MOUNT" == "1" ]; then
    sudo umount -l $CHROOTDIR/proc/sys/fs/binfmt_misc $CHROOTDIR/proc $CHROOTDIR/dev/pts $CHROOTDIR/dev $CHROOTDIR/sys
  fi

# change user once in chroot
elif [ "$STEP" == "user" ]; then

  # used for start exe without wine prefix
  if [ -x /etc/init.d/binfmt-support ]; then
    /etc/init.d/binfmt-support start
  fi

  su -l -c "$ARGS" openturns
fi



